name: build on pr

on:
  pull_request:
    branches:
      - main

jobs:
  build_on_pr:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Login into docker
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker image
        run: |
          docker build -t harshithreddy6322/nodecpu:latest .
      - name: Push to docker
        run: |
          docker push harshithreddy6322/nodecpu:latest
      - name: Verify image
        run: |
          docker pull 100xdevs/web-app:latest
